#!/bin/bash

# Quick reference for testing products routes with curl
# Copy and paste these commands into your terminal

BASE_URL="http://localhost:5000/api/products"

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║           QUICK CURL REFERENCE FOR PRODUCTS ROUTES                ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""
echo "Set BASE_URL: BASE_URL=http://localhost:5000/api/products"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "1. SINGLE PRODUCT ENDPOINTS"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "# Get product by ID (full details)"
echo "curl -s \$BASE_URL/1 | jq '.'"
echo ""
echo "# Get product by slug"
echo "curl -s \$BASE_URL/slug/some-product-slug | jq '.'"
echo ""
echo "# Get with pretty formatting"
echo "curl -s \$BASE_URL/1 | jq '{id, name, price, sale_price, stock}'"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "2. LIST ENDPOINTS"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "# Basic list (page 1, 20 items)"
echo "curl -s \"\$BASE_URL/?page=1&per_page=20\" | jq '.'"
echo ""
echo "# Get just product names and prices"
echo "curl -s \"\$BASE_URL/?page=1&per_page=5\" | jq '.items[] | {name, price}'"
echo ""
echo "# Check pagination"
echo "curl -s \"\$BASE_URL/?page=1&per_page=10\" | jq '.pagination'"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "3. FAST ENDPOINT (Optimized)"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "# Get lightweight products (minimal fields)"
echo "curl -s \"\$BASE_URL/fast?page=1&per_page=20\" | jq '.'"
echo ""
echo "# Time comparison: normal vs fast"
echo "time curl -s \"\$BASE_URL/?page=1&per_page=20\" > /dev/null"
echo "time curl -s \"\$BASE_URL/fast?page=1&per_page=20\" > /dev/null"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "4. FILTERING"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "# Featured products"
echo "curl -s \"\$BASE_URL/?is_featured=true&per_page=5\" | jq '.'"
echo ""
echo "# Sale products"
echo "curl -s \"\$BASE_URL/?is_sale=true&per_page=5\" | jq '.'"
echo ""
echo "# By category ID"
echo "curl -s \"\$BASE_URL/?category_id=1&per_page=5\" | jq '.'"
echo ""
echo "# By price range"
echo "curl -s \"\$BASE_URL/?min_price=10&max_price=100&per_page=5\" | jq '.'"
echo ""
echo "# Combine filters"
echo "curl -s \"\$BASE_URL/?is_featured=true&category_id=1&per_page=5\" | jq '.'"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "5. BOOLEAN NORMALIZATION TEST"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "# These should return identical results (tests cache key normalization)"
echo "curl -s \"\$BASE_URL/fast?is_featured=true\" | jq '.items | length'"
echo "curl -s \"\$BASE_URL/fast?is_featured=1\" | jq '.items | length'"
echo "curl -s \"\$BASE_URL/fast?is_featured=yes\" | jq '.items | length'"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "6. FEATURED SECTIONS"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "# Trending products"
echo "curl -s \"\$BASE_URL/trending?limit=10\" | jq '.items[]'"
echo ""
echo "# Flash sale"
echo "curl -s \"\$BASE_URL/flash_sale?limit=10\" | jq '.'"
echo ""
echo "# New arrivals"
echo "curl -s \"\$BASE_URL/new_arrivals?limit=10\" | jq '.'"
echo ""
echo "# Top picks"
echo "curl -s \"\$BASE_URL/top_picks?limit=10\" | jq '.'"
echo ""
echo "# Daily finds"
echo "curl -s \"\$BASE_URL/daily_finds?limit=10\" | jq '.'"
echo ""
echo "# Luxury deals"
echo "curl -s \"\$BASE_URL/luxury_deals?limit=10\" | jq '.'"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "7. FAST FEATURED SECTIONS"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "# Fast trending (minimal fields)"
echo "curl -s \"\$BASE_URL/trending/fast?limit=10\" | jq '.'"
echo ""
echo "# Fast flash sale"
echo "curl -s \"\$BASE_URL/flash_sale/fast?limit=10\" | jq '.'"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "8. CACHE BEHAVIOR"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "# Check cache hit (headers)"
echo "curl -s -i \"\$BASE_URL/1\" | grep -i 'x-cache'"
echo ""
echo "# Time the same request twice (cache hit should be faster)"
echo "curl -w '%{time_total}\\n' -o /dev/null -s \"\$BASE_URL/1\""
echo "curl -w '%{time_total}\\n' -o /dev/null -s \"\$BASE_URL/1\""
echo ""
echo "# Get cache info"
echo "curl -s \"\$BASE_URL/cache/info\" | jq '.'"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "9. ERROR HANDLING"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "# Test 404 on non-existent product"
echo "curl -i \"\$BASE_URL/99999999\""
echo ""
echo "# Test 404 on non-existent slug"
echo "curl -i \"\$BASE_URL/slug/this-does-not-exist\""
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "10. SERIALIZATION QUALITY"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "# Compare field counts: full vs lightweight"
echo "echo 'Full product fields:'; curl -s \"\$BASE_URL/1\" | jq 'keys | length'"
echo "echo 'Lightweight fields:'; curl -s \"\$BASE_URL/?page=1&per_page=1\" | jq '.items[0] | keys | length'"
echo ""
echo "# Show field differences"
echo "echo 'Full fields:'; curl -s \"\$BASE_URL/1\" | jq 'keys | sort'"
echo "echo 'Lightweight fields:'; curl -s \"\$BASE_URL/?page=1&per_page=1\" | jq '.items[0] | keys | sort'"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "11. SEARCH & SORTING"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "# Search products"
echo "curl -s \"\$BASE_URL/?search=laptop&per_page=5\" | jq '.'"
echo ""
echo "# Sort by price ascending"
echo "curl -s \"\$BASE_URL/?sort_by=price&sort_order=asc&per_page=5\" | jq '.'"
echo ""
echo "# Sort by created date descending"
echo "curl -s \"\$BASE_URL/?sort_by=created_at&sort_order=desc&per_page=5\" | jq '.'"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "HELPFUL TIPS"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "# Install jq if needed:"
echo "  # macOS: brew install jq"
echo "  # Ubuntu: sudo apt install jq"
echo ""
echo "# Run the full test suite:"
echo "  bash scripts/test-products-curl.sh"
echo ""
echo "# Run Python test suite (comprehensive):"
echo "  python scripts/test_products_api.py"
echo ""
echo "# Pretty print JSON:"
echo "  curl -s \$URL | jq ."
echo ""
echo "# Extract specific fields:"
echo "  curl -s \$URL | jq '.name, .price, .slug'"
echo ""
echo "# Filter array:"
echo "  curl -s \$URL | jq '.items[] | select(.price > 50)'"
echo ""
echo "# Count items:"
echo "  curl -s \$URL | jq '.items | length'"
echo ""
echo "# Measure response time:"
echo "  curl -w '%{time_total}\\n' -o /dev/null -s \$URL"
echo ""
echo "# Check HTTP headers:"
echo "  curl -i \$URL"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
