"""Initial migration

Revision ID: 5834bd9e45c4
Revises: 02ebd12fb586
Create Date: 2025-11-27 17:15:46.245517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5834bd9e45c4'
down_revision = '02ebd12fb586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theme_presets')
    op.drop_table('footer_settings')
    with op.batch_alter_table('topbar_slides', schema=None) as batch_op:
        batch_op.drop_index('ix_topbar_slides_is_active')
        batch_op.drop_index('ix_topbar_slides_sort_order')

    op.drop_table('topbar_slides')
    op.drop_table('theme_settings')
    op.drop_table('notification_preferences')
    with op.batch_alter_table('carousel_banners', schema=None) as batch_op:
        batch_op.drop_index('ix_carousel_banners_is_active')
        batch_op.drop_index('ix_carousel_banners_name')
        batch_op.drop_index('ix_carousel_banners_position')
        batch_op.drop_index('ix_carousel_banners_sort_order')

    op.drop_table('carousel_banners')
    with op.batch_alter_table('contact_cta_slides', schema=None) as batch_op:
        batch_op.drop_index('ix_contact_cta_slides_is_active')
        batch_op.drop_index('ix_contact_cta_slides_sort_order')

    op.drop_table('contact_cta_slides')
    with op.batch_alter_table('side_panels', schema=None) as batch_op:
        batch_op.drop_index('ix_side_panels_is_active')
        batch_op.drop_index('ix_side_panels_panel_type')
        batch_op.drop_index('ix_side_panels_position')
        batch_op.drop_index('ix_side_panels_sort_order')

    op.drop_table('side_panels')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('idx_user_read_created')
        batch_op.drop_index('idx_user_type')
        batch_op.drop_index('ix_notifications_created_at')
        batch_op.drop_index('ix_notifications_read')
        batch_op.drop_index('ix_notifications_user_id')

    op.drop_table('notifications')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('image_mimetype',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('banner_mimetype',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('banner_mimetype',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('image_mimetype',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('ORDER', 'PAYMENT', 'SHIPPING', 'SYSTEM', 'PROMOTION', 'PRODUCT', 'ANNOUNCEMENT', 'PRODUCT_UPDATE', 'PRICE_CHANGE', 'STOCK_ALERT', name='notificationtype'), autoincrement=False, nullable=False),
    sa.Column('priority', postgresql.ENUM('HIGH', 'MEDIUM', 'NORMAL', 'LOW', name='notificationpriority'), autoincrement=False, nullable=True),
    sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('badge', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='notifications_order_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='notifications_product_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_notifications_read', ['read'], unique=False)
        batch_op.create_index('ix_notifications_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_user_type', ['user_id', 'type'], unique=False)
        batch_op.create_index('idx_user_read_created', ['user_id', 'read', 'created_at'], unique=False)

    op.create_table('side_panels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('panel_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('metric', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('icon_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('gradient', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='side_panels_pkey')
    )
    with op.batch_alter_table('side_panels', schema=None) as batch_op:
        batch_op.create_index('ix_side_panels_sort_order', ['sort_order'], unique=False)
        batch_op.create_index('ix_side_panels_position', ['position'], unique=False)
        batch_op.create_index('ix_side_panels_panel_type', ['panel_type'], unique=False)
        batch_op.create_index('ix_side_panels_is_active', ['is_active'], unique=False)

    op.create_table('contact_cta_slides',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subtitle', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('gradient', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('accent_color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='contact_cta_slides_pkey')
    )
    with op.batch_alter_table('contact_cta_slides', schema=None) as batch_op:
        batch_op.create_index('ix_contact_cta_slides_sort_order', ['sort_order'], unique=False)
        batch_op.create_index('ix_contact_cta_slides_is_active', ['is_active'], unique=False)

    op.create_table('carousel_banners',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('badge_text', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('discount', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('button_text', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('link_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='carousel_banners_pkey')
    )
    with op.batch_alter_table('carousel_banners', schema=None) as batch_op:
        batch_op.create_index('ix_carousel_banners_sort_order', ['sort_order'], unique=False)
        batch_op.create_index('ix_carousel_banners_position', ['position'], unique=False)
        batch_op.create_index('ix_carousel_banners_name', ['name'], unique=False)
        batch_op.create_index('ix_carousel_banners_is_active', ['is_active'], unique=False)

    op.create_table('notification_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('payment', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('product', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('promotion', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('system', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('announcement', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('product_update', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('price_change', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('stock_alert', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('push_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sms_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notification_preferences_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notification_preferences_pkey'),
    sa.UniqueConstraint('user_id', name='notification_preferences_user_id_key')
    )
    op.create_table('theme_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('primary_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('primary_light', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('primary_dark', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('secondary_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('accent_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('background_color', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('card_background', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('surface_color', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('text_primary', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('text_secondary', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('text_on_primary', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('border_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('divider_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('button_primary_bg', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('button_primary_text', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('button_primary_hover', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('button_secondary_bg', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('button_secondary_text', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('success_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('warning_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('error_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('info_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('header_background', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('header_text', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('footer_background', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('footer_text', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('link_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('link_hover_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('badge_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('badge_text', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('nav_background', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('nav_text', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('nav_active', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('carousel_background', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('carousel_overlay_dark', sa.VARCHAR(length=19), autoincrement=False, nullable=False),
    sa.Column('carousel_overlay_light', sa.VARCHAR(length=19), autoincrement=False, nullable=False),
    sa.Column('carousel_badge_bg', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('carousel_badge_text', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='theme_settings_created_by_fkey'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='theme_settings_updated_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='theme_settings_pkey')
    )
    op.create_table('topbar_slides',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('campaign', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subtext', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bg_color', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('product_image_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('product_alt', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('center_content_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('center_content_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('button_text', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('button_link', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='topbar_slides_pkey')
    )
    with op.batch_alter_table('topbar_slides', schema=None) as batch_op:
        batch_op.create_index('ix_topbar_slides_sort_order', ['sort_order'], unique=False)
        batch_op.create_index('ix_topbar_slides_is_active', ['is_active'], unique=False)

    op.create_table('footer_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('background_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('newsletter_bg_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('text_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('secondary_text_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('accent_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('link_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('link_hover_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('newsletter_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('newsletter_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('company_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tagline', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('business_hours', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('facebook_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('instagram_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('twitter_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('youtube_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('tiktok_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('linkedin_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('need_help_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('about_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('categories', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('useful_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resources_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('payment_methods', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('copyright_text', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='footer_settings_pkey')
    )
    op.create_table('theme_presets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('thumbnail_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('theme_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='theme_presets_pkey')
    )
    # ### end Alembic commands ###
